import streamlit as st
import plotly.express as px
from utils import preprocess_data, apply_filters
import pandas as pd

st.set_page_config(page_title="Teacher Analysis", layout="wide")

df = preprocess_data()

# ==========================
# Teacher Analysis Filters
# ==========================

st.sidebar.header("🔎 Filters")

df["TransactionDate"] = pd.to_datetime(df["TransactionDate"])

min_date = df["TransactionDate"].min().date()
max_date = df["TransactionDate"].max().date()

date_range = st.sidebar.date_input(
    "📅 Transaction Date",
    value=(min_date, max_date),
    min_value=min_date,
    max_value=max_date
)

teacher_filter = st.sidebar.multiselect(
    "👨‍🏫 Teacher",
    sorted(df["TeacherName"].dropna().unique()),
    default=sorted(df["TeacherName"].dropna().unique())
)

category_filter = st.sidebar.multiselect(
    "📚 Course Category",
    sorted(df["CourseCategory"].dropna().unique()),
    default=sorted(df["CourseCategory"].dropna().unique())
)

level_filter = st.sidebar.multiselect(
    "🎓 Course Level",
    sorted(df["CourseLevel"].dropna().unique()),
    default=sorted(df["CourseLevel"].dropna().unique())
)

if len(date_range) == 2:

    df = df[
        (df["TransactionDate"] >= pd.Timestamp(date_range[0])) &
        (df["TransactionDate"] <= pd.Timestamp(date_range[1])) &
        (df["TeacherName"].isin(teacher_filter)) &
        (df["CourseCategory"].isin(category_filter)) &
        (df["CourseLevel"].isin(level_filter))
    ]

st.title("👨‍🏫 Teacher Analysis Dashboard")

st.markdown("Analyze teacher performance, ratings, experience and generated revenue.")

# ---------------- KPI Cards ----------------

total_teachers = df["TeacherID"].nunique()
avg_rating = round(df["TeacherRating"].mean(), 2)
avg_exp = round(df["YearsOfExperience"].mean(), 1)
total_revenue = df["Amount"].sum()

c1, c2, c3, c4 = st.columns(4)

c1.metric("Total Teachers", total_teachers)
c2.metric("Average Rating", avg_rating)
c3.metric("Average Experience", f"{avg_exp} Years")
c4.metric("Revenue Generated", f"${total_revenue:,.0f}")

st.divider()

# ----------------------------------------------------
# Teacher Performance
# ----------------------------------------------------

teacher_summary = (
    df.groupby("TeacherName")
    .agg(
        Revenue=("Amount", "sum"),
        Enrollments=("TransactionID", "count")
    )
    .sort_values("Revenue", ascending=False)
    .reset_index()
)

# Revenue Generated by Teacher

fig1 = px.bar(
    teacher_summary,
    x="TeacherName",
    y="Revenue",
    color="Revenue",
    title="Revenue Generated by Teacher"
)

st.plotly_chart(
    fig1,
    use_container_width=True
)

# ----------------------------------------------------
# Teacher Ratings
# ----------------------------------------------------

fig2 = px.histogram(
    df,
    x="TeacherRating",
    nbins=10,
    title="Teacher Rating Distribution"
)

st.plotly_chart(fig2, use_container_width=True)

# ----------------------------------------------------
# Experience Distribution
# ----------------------------------------------------

fig3 = px.histogram(
    df,
    x="YearsOfExperience",
    nbins=15,
    title="Teacher Experience Distribution"
)

st.plotly_chart(fig3, use_container_width=True)

# ----------------------------------------------------
# Rating vs Revenue
# ----------------------------------------------------

teacher_rating_summary = (
    df.groupby(["TeacherName", "TeacherRating"])
    .agg(Revenue=("Amount", "sum"))
    .reset_index()
)
fig4 = px.scatter(
    teacher_rating_summary,
    x="TeacherRating",
    y="Revenue",
    hover_name="TeacherName",
    size="Revenue",
    color="Revenue",
    title="Teacher Rating vs Revenue"
)

st.plotly_chart(fig4, use_container_width=True)

# ----------------------------------------------------
# Experience vs Revenue
# ----------------------------------------------------

teacher_exp = (
    df.groupby(["TeacherName", "YearsOfExperience"])
      .agg(Revenue=("Amount", "sum"))
      .reset_index()
)

fig5 = px.scatter(
    teacher_exp,
    x="YearsOfExperience",
    y="Revenue",
    hover_name="TeacherName",
    size="Revenue",
    color="Revenue",
    title="Experience vs Revenue"
)

st.plotly_chart(fig5, use_container_width=True)

# ----------------------------------------------------
# Gender Distribution
# ----------------------------------------------------

gender = (
    df.groupby("Gender_y")
      .size()
      .reset_index(name="Count")
)

fig6 = px.pie(
    gender,
    names="Gender_y",
    values="Count",
    title="Teacher Gender Distribution"
)

st.plotly_chart(fig6, use_container_width=True)

# ----------------------------------------------------
# Top 10 Teachers
# ----------------------------------------------------

top10 = teacher_summary.head(10)

fig7 = px.bar(
    top10,
    x="TeacherName",
    y="Revenue",
    color="Revenue",
    title="Top 10 Teachers by Revenue"
)

st.plotly_chart(
    fig7,
    use_container_width=True
)

top10_enrollment = (
    teacher_summary
    .sort_values("Enrollments", ascending=False)
    .head(10)
)

fig8 = px.bar(
    top10_enrollment,
    x="TeacherName",
    y="Enrollments",
    color="Enrollments",
    title="🎓 Top 10 Teachers by Enrollments"
)

st.plotly_chart(
    fig8,
    use_container_width=True
)

# ----------------------------------------------------
# Teacher Information
# ----------------------------------------------------

st.subheader("Teacher Information")

teacher_table = df[
    [
        "TeacherName",
        "Expertise",
        "YearsOfExperience",
        "TeacherRating",
        "Gender_y"
    ]
].drop_duplicates()

st.dataframe(teacher_table, use_container_width=True)
st.download_button(
    label="📥 Download Teacher Data",
    data=teacher_table.to_csv(index=False),
    file_name="Teacher_Data.csv",
    mime="text/csv"
)
